# Generated by Django 5.0.6 on 2025-01-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
