# Generated by Django 5.0.6 on 2025-01-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_accident_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='unknown',
            field=models.CharField(default='情况未知', max_length=200),
        ),
    ]
