# Generated by Django 5.0.6 on 2025-01-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_accident_unknown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='is_approved',
            field=models.BooleanField(verbose_name=False),
        ),
        migrations.AlterField(
            model_name='accident',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='accident',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
